using System;  
public class ExExample  
{  
    /* public static void Main(string[] args)  
    {  
        try  
        {  
            int a = 10;  
            int b = 0;  
            int x = a / b;  
        }  
        catch (NullReferenceException e) { Console.WriteLine(e); }  
        finally { Console.WriteLine("Finally block is executed"); }  
        Console.WriteLine("Rest of the code");  
        //If we handle wrong exception the finally block will execute even tough you catch a wrong exception.
        //output will be:
        // Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
        // at ExExample.Main(String[] args) in D:\Projects\Sitecore\exceptionHandling\finallyExcepNotHandled.cs:line 10
        // Finally block is executed
        //since we have handled wrong exception the REst of the code won't execute.
    }  */ 
}  